### ISSUE TITLE
potential divide by zero?

### ISSUE THREAD

**Issue by Yahoo-Mike** [michel-leonard/C-Quadratic-Sieve#2]
Is that an intentional divide-by-zero at [line 218](https://github.com/michel-leonard/C-Quadratic-Sieve/blob/f29f9c00dec02ca8b7bee3b0dc4b925aae75e63c/fac_utils.c#L218) of _fac_utils.c_ ?
`	} else b = (n == 0) / 0.;`

Also, at [line 55](https://github.com/michel-leonard/C-Quadratic-Sieve/blob/f29f9c00dec02ca8b7bee3b0dc4b925aae75e63c/cint.c#L55) of _cint.c_, is there any reason why cint_clear_sheet() is not also static ?
`void cint_clear_sheet(cint_sheet *sheet) {`

**Comment by michel-leonard** [comment]
Hello and thank you,

Logarithms are only defined with positive values, so the branch `b = (n == 0) / 0.` branch should never be taken by this software, this fatal error it's a normal behavior with logarithms.

The `cint_clear_sheet` function has no reason not to be static, it's upadated, thanks.

**Comment by michel-leonard** [comment]
Hello and thank you,

The `b = (n == 0) / 0.` branch should never be taken by this software, this fatal error it's a normal behavior with logarithms (they are defined with positive numbers only).

The `cint_clear_sheet` function has no reason not to be static, it's upadated, thanks.

**Comment by Yahoo-Mike** [comment]
Makes sense.  Thanks.
